/* eslint-disable @typescript-eslint/naming-convention */
import './global.css';
import React from 'react';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '../lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata = {
  title: 'Welcome to example-app',
  description: 'Generated by create-nx-workspace',
};

export default function rootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
