name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'  # Run on all pull requests targeting any branch

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'  # Use pnpm cache

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Nx Lint
        run: pnpm nx run-many --target=lint --all

      - name: Build Packages
        run: pnpm nx run-many --target=build --all
