name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          PROJECTS=("abstract-core" "abstract-evm")
          for project in "${PROJECTS[@]}"; do
            echo "Building $project..."
            pnpm exec nx build $project --with-deps=true
            
            echo "Publishing $project..."
            cd dist/libs/$project
            pnpm publish --access public
            cd ../../../
          done
